// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bids.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkBidExists = `-- name: CheckBidExists :one
SELECT COUNT(*) as count
FROM tender_bids 
WHERE tender_id = $1 AND amount = $2
`

type CheckBidExistsParams struct {
	TenderID int32   `json:"tender_id"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) CheckBidExists(ctx context.Context, arg CheckBidExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkBidExists, arg.TenderID, arg.Amount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBid = `-- name: CreateBid :exec
INSERT INTO tender_bids (tender_id, user_id, amount, bid_time) 
VALUES ($1, $2, $3, $4)
`

type CreateBidParams struct {
	TenderID int32              `json:"tender_id"`
	UserID   int64              `json:"user_id"`
	Amount   float64            `json:"amount"`
	BidTime  pgtype.Timestamptz `json:"bid_time"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) error {
	_, err := q.db.Exec(ctx, createBid,
		arg.TenderID,
		arg.UserID,
		arg.Amount,
		arg.BidTime,
	)
	return err
}

const getBidsAfterTime = `-- name: GetBidsAfterTime :many
SELECT id, tender_id, user_id, amount, bid_time FROM tender_bids 
WHERE tender_id = $1 AND bid_time > $2 
ORDER BY bid_time DESC
`

type GetBidsAfterTimeParams struct {
	TenderID int32              `json:"tender_id"`
	BidTime  pgtype.Timestamptz `json:"bid_time"`
}

func (q *Queries) GetBidsAfterTime(ctx context.Context, arg GetBidsAfterTimeParams) ([]TenderBid, error) {
	rows, err := q.db.Query(ctx, getBidsAfterTime, arg.TenderID, arg.BidTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenderBid{}
	for rows.Next() {
		var i TenderBid
		if err := rows.Scan(
			&i.ID,
			&i.TenderID,
			&i.UserID,
			&i.Amount,
			&i.BidTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBidsHistoryByTenderID = `-- name: GetBidsHistoryByTenderID :many
SELECT 
    b.amount,
    b.bid_time,
    u.organization_name
FROM tender_bids b
JOIN users u ON b.user_id = u.telegram_id
WHERE b.tender_id = $1
ORDER BY b.bid_time ASC
`

type GetBidsHistoryByTenderIDRow struct {
	Amount           float64            `json:"amount"`
	BidTime          pgtype.Timestamptz `json:"bid_time"`
	OrganizationName pgtype.Text        `json:"organization_name"`
}

func (q *Queries) GetBidsHistoryByTenderID(ctx context.Context, tenderID int32) ([]GetBidsHistoryByTenderIDRow, error) {
	rows, err := q.db.Query(ctx, getBidsHistoryByTenderID, tenderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBidsHistoryByTenderIDRow{}
	for rows.Next() {
		var i GetBidsHistoryByTenderIDRow
		if err := rows.Scan(&i.Amount, &i.BidTime, &i.OrganizationName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBidCount = `-- name: GetUserBidCount :one
SELECT COUNT(*) FROM tender_bids
WHERE tender_id = $1 AND user_id = $2
`

type GetUserBidCountParams struct {
	TenderID int32 `json:"tender_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) GetUserBidCount(ctx context.Context, arg GetUserBidCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserBidCount, arg.TenderID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserBidsForTender = `-- name: GetUserBidsForTender :many
SELECT id, tender_id, user_id, amount, bid_time FROM tender_bids 
WHERE tender_id = $1 AND user_id = $2 
ORDER BY bid_time DESC
`

type GetUserBidsForTenderParams struct {
	TenderID int32 `json:"tender_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) GetUserBidsForTender(ctx context.Context, arg GetUserBidsForTenderParams) ([]TenderBid, error) {
	rows, err := q.db.Query(ctx, getUserBidsForTender, arg.TenderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenderBid{}
	for rows.Next() {
		var i TenderBid
		if err := rows.Scan(
			&i.ID,
			&i.TenderID,
			&i.UserID,
			&i.Amount,
			&i.BidTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenderCurrentPrice = `-- name: UpdateTenderCurrentPrice :exec
UPDATE tenders 
SET current_price = $2
WHERE id = $1
`

type UpdateTenderCurrentPriceParams struct {
	ID           int32   `json:"id"`
	CurrentPrice float64 `json:"current_price"`
}

func (q *Queries) UpdateTenderCurrentPrice(ctx context.Context, arg UpdateTenderCurrentPriceParams) error {
	_, err := q.db.Exec(ctx, updateTenderCurrentPrice, arg.ID, arg.CurrentPrice)
	return err
}
