// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drop_db.sql

package db

import (
	"context"
)

const dropDb = `-- name: DropDb :exec
TRUNCATE TABLE 
    history, 
    tender_bids, 
    tender_participants, 
    pending_users,
	tenders,
	users
CASCADE
`

func (q *Queries) DropDb(ctx context.Context) error {
	_, err := q.db.Exec(ctx, dropDb)
	return err
}
