// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToHistory = `-- name: AddToHistory :exec
INSERT INTO history (tender_id, title, winner, phone_number, inn, fio, bid, start_price)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AddToHistoryParams struct {
	TenderID    int32       `json:"tender_id"`
	Title       string      `json:"title"`
	Winner      pgtype.Text `json:"winner"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	Inn         pgtype.Text `json:"inn"`
	Fio         pgtype.Text `json:"fio"`
	Bid         float64     `json:"bid"`
	StartPrice  float64     `json:"start_price"`
}

func (q *Queries) AddToHistory(ctx context.Context, arg AddToHistoryParams) error {
	_, err := q.db.Exec(ctx, addToHistory,
		arg.TenderID,
		arg.Title,
		arg.Winner,
		arg.PhoneNumber,
		arg.Inn,
		arg.Fio,
		arg.Bid,
		arg.StartPrice,
	)
	return err
}

const getTendersHistory = `-- name: GetTendersHistory :many
SELECT id, tender_id, title, winner, phone_number, inn, fio, bid, start_price, created_at FROM history ORDER BY created_at ASC
`

func (q *Queries) GetTendersHistory(ctx context.Context) ([]History, error) {
	rows, err := q.db.Query(ctx, getTendersHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []History{}
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.TenderID,
			&i.Title,
			&i.Winner,
			&i.PhoneNumber,
			&i.Inn,
			&i.Fio,
			&i.Bid,
			&i.StartPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
