// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tender struct {
	ID                int32              `json:"id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	StartPrice        float64            `json:"start_price"`
	StartAt           pgtype.Timestamptz `json:"start_at"`
	Status            string             `json:"status"`
	ConditionsPath    pgtype.Text        `json:"conditions_path"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Classification    pgtype.Text        `json:"classification"`
	ParticipantsCount int32              `json:"participants_count"`
	LastBidAt         pgtype.Timestamptz `json:"last_bid_at"`
	CurrentPrice      float64            `json:"current_price"`
	MinBidDecrease    float64            `json:"min_bid_decrease"`
}

type TenderBid struct {
	ID       int32              `json:"id"`
	TenderID int32              `json:"tender_id"`
	UserID   int64              `json:"user_id"`
	Amount   float64            `json:"amount"`
	BidTime  pgtype.Timestamptz `json:"bid_time"`
}

type TenderParticipant struct {
	ID       int32 `json:"id"`
	TenderID int32 `json:"tender_id"`
	UserID   int64 `json:"user_id"`
}

type User struct {
	TelegramID       int64       `json:"telegram_id"`
	OrganizationName pgtype.Text `json:"organization_name"`
	Inn              pgtype.Text `json:"inn"`
	Ogrn             pgtype.Text `json:"ogrn"`
	PhoneNumber      pgtype.Text `json:"phone_number"`
	Classification   pgtype.Text `json:"classification"`
	Role             string      `json:"role"`
	Banned           pgtype.Bool `json:"banned"`
	Name             pgtype.Text `json:"name"`
}
