// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
)

const getParticipantsForTender = `-- name: GetParticipantsForTender :many
SELECT user_id FROM tender_participants 
WHERE tender_id = $1
`

func (q *Queries) GetParticipantsForTender(ctx context.Context, tenderID int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, getParticipantsForTender, tenderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
