// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
)

const getParticipantNumber = `-- name: GetParticipantNumber :one
SELECT COUNT(*) + 1 as participant_number
FROM tender_participants tp1
WHERE tp1.tender_id = $1 
AND tp1.joined_at < (
    SELECT joined_at 
    FROM tender_participants tp2 
    WHERE tp2.tender_id = $1 AND tp2.user_id = $2
)
`

type GetParticipantNumberParams struct {
	TenderID int32 `json:"tender_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) GetParticipantNumber(ctx context.Context, arg GetParticipantNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, getParticipantNumber, arg.TenderID, arg.UserID)
	var participant_number int32
	err := row.Scan(&participant_number)
	return participant_number, err
}

const getParticipantsForTender = `-- name: GetParticipantsForTender :many
SELECT user_id FROM tender_participants 
WHERE tender_id = $1
`

func (q *Queries) GetParticipantsForTender(ctx context.Context, tenderID int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, getParticipantsForTender, tenderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenderFromParticipants = `-- name: GetTenderFromParticipants :one
select (tender_id) from tender_participants 
where user_id = $1
`

func (q *Queries) GetTenderFromParticipants(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, getTenderFromParticipants, userID)
	var tender_id int32
	err := row.Scan(&tender_id)
	return tender_id, err
}

const removeParticipants = `-- name: RemoveParticipants :exec
DELETE FROM tender_participants WHERE tender_id = $1
`

func (q *Queries) RemoveParticipants(ctx context.Context, tenderID int32) error {
	_, err := q.db.Exec(ctx, removeParticipants, tenderID)
	return err
}
