// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePendingUser = `-- name: ApprovePendingUser :exec
DELETE FROM pending_users WHERE telegram_id = $1
`

func (q *Queries) ApprovePendingUser(ctx context.Context, telegramID int64) error {
	_, err := q.db.Exec(ctx, approvePendingUser, telegramID)
	return err
}

const createPendingUser = `-- name: CreatePendingUser :exec
INSERT INTO pending_users (
    telegram_id, 
    organization_name, 
    inn, 
    phone_number, 
    name, 
    classification,
    created_at
) VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type CreatePendingUserParams struct {
	TelegramID       int64       `json:"telegram_id"`
	OrganizationName pgtype.Text `json:"organization_name"`
	Inn              pgtype.Text `json:"inn"`
	PhoneNumber      pgtype.Text `json:"phone_number"`
	Name             pgtype.Text `json:"name"`
	Classification   pgtype.Text `json:"classification"`
}

func (q *Queries) CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) error {
	_, err := q.db.Exec(ctx, createPendingUser,
		arg.TelegramID,
		arg.OrganizationName,
		arg.Inn,
		arg.PhoneNumber,
		arg.Name,
		arg.Classification,
	)
	return err
}

const getAllPendingUsers = `-- name: GetAllPendingUsers :many
SELECT id, telegram_id, organization_name, inn, phone_number, name, classification, created_at FROM pending_users ORDER BY created_at DESC
`

func (q *Queries) GetAllPendingUsers(ctx context.Context) ([]PendingUser, error) {
	rows, err := q.db.Query(ctx, getAllPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingUser{}
	for rows.Next() {
		var i PendingUser
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.OrganizationName,
			&i.Inn,
			&i.PhoneNumber,
			&i.Name,
			&i.Classification,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingUser = `-- name: GetPendingUser :one
SELECT id, telegram_id, organization_name, inn, phone_number, name, classification, created_at FROM pending_users WHERE telegram_id = $1
`

func (q *Queries) GetPendingUser(ctx context.Context, telegramID int64) (PendingUser, error) {
	row := q.db.QueryRow(ctx, getPendingUser, telegramID)
	var i PendingUser
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.OrganizationName,
		&i.Inn,
		&i.PhoneNumber,
		&i.Name,
		&i.Classification,
		&i.CreatedAt,
	)
	return i, err
}
