// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ActivatePendingTenders(ctx context.Context) error
	ApproveTender(ctx context.Context, id int32) error
	CheckTenderParticipation(ctx context.Context, arg CheckTenderParticipationParams) (bool, error)
	CreateTender(ctx context.Context, arg CreateTenderParams) (Tender, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTender(ctx context.Context, id int32) error
	GetHistory(ctx context.Context) ([]Tender, error)
	GetTender(ctx context.Context, id int32) (Tender, error)
	GetTenders(ctx context.Context) ([]Tender, error)
	GetTendersForDeletion(ctx context.Context) ([]Tender, error)
	GetTendersForSuppliers(ctx context.Context, arg GetTendersForSuppliersParams) ([]Tender, error)
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	JoinTender(ctx context.Context, arg JoinTenderParams) error
	LeaveTender(ctx context.Context, arg LeaveTenderParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
