// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	ActivatePendingTenders(ctx context.Context) error
	ApproveTender(ctx context.Context, id int32) error
	CheckTenderParticipation(ctx context.Context, arg CheckTenderParticipationParams) (bool, error)
	CheckUserHasAnyTenderParticipation(ctx context.Context, arg CheckUserHasAnyTenderParticipationParams) (bool, error)
	CreateBid(ctx context.Context, arg CreateBidParams) error
	CreateTender(ctx context.Context, arg CreateTenderParams) (Tender, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTender(ctx context.Context, id int32) error
	GetBidsAfterTime(ctx context.Context, arg GetBidsAfterTimeParams) ([]TenderBid, error)
	GetHistory(ctx context.Context) ([]Tender, error)
	GetParticipantsForTender(ctx context.Context, tenderID int32) ([]int64, error)
	GetStartingTenders(ctx context.Context) ([]GetStartingTendersRow, error)
	GetTender(ctx context.Context, id int32) (Tender, error)
	GetTenderById(ctx context.Context, id int32) (Tender, error)
	GetTenderFromParticipants(ctx context.Context, userID int64) (int32, error)
	GetTenders(ctx context.Context) ([]Tender, error)
	GetTendersForDeletion(ctx context.Context) ([]Tender, error)
	GetTendersForSuppliers(ctx context.Context, arg GetTendersForSuppliersParams) ([]Tender, error)
	GetTendersStartingIn5Minutes(ctx context.Context) ([]GetTendersStartingIn5MinutesRow, error)
	GetUserBidCount(ctx context.Context, arg GetUserBidCountParams) (int64, error)
	GetUserBidsForTender(ctx context.Context, arg GetUserBidsForTenderParams) ([]TenderBid, error)
	GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error)
	JoinTender(ctx context.Context, arg JoinTenderParams) error
	LeaveTender(ctx context.Context, arg LeaveTenderParams) error
	RemoveParticipants(ctx context.Context, tenderID int32) error
	UpdateTenderCurrentPrice(ctx context.Context, arg UpdateTenderCurrentPriceParams) error
	UpdateTenderStatus(ctx context.Context, arg UpdateTenderStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
